### PR TITLE
Add AutoEvents

### LINKED ISSUE #8: Add AutoEvents
Add AutoEvents to get device resources periodically
reference: [device-sdk-go/example/cmd/device-simple/res/configuration.toml](https://github.com/edgexfoundry/device-sdk-go/blob/master/example/cmd/device-simple/res/configuration.toml#L68)

### PR DESCRIPTION
**Pull request by FelixTing**
Close #8 

Signed-off-by: Felix Ting <felix@iotechsys.com>

### CODE REVIEW

**Comment by lenny-intel** [comment]
@FelixTing, will you be completing this PR this week?
I am depending on device virtual with auto events for our App Functions training in Seoul. ;-) Thx.

**Comment by cloudxxx8** [comment]
recheck

**Comment by cloudxxx8** [comment]
LGTM, but the validation task should be revised

**Comment by lenny-intel** [comment]
@cloudxxx8 , Thx! ;-)

**Comment by FelixTing** [comment]
> LGTM, but the validation task should be revised
about the validation task, it needs DevOps WG help to set the SETTINGS_FILE for device-virtual-go jobs on jenkins

**Pull request merged**
